#!/bin/bash
# git-cheats.sh — Quick Git command reference for PatientLead Plus

echo ""
echo "=== PatientLead Plus: Git Cheatsheet ==="
echo ""
echo "0) Check status:"
echo "   git status"
echo ""
echo "1) See what changed:"
echo "   git diff"
echo ""
echo "2) Stage changes:"
echo "   git add -A          # all changes"
echo "   git add path/to/file  # specific file(s)"
echo ""
echo "3) Commit changes:"
echo '   git commit -m "Your message"'
echo ""
echo "4) Push to GitHub:"
echo "   git push"
echo ""
echo "5) Common fixes:"
echo "   git commit --amend -m \"Fix last commit msg\""
echo "   git reset HEAD path/to/file   # unstage file"
echo "   git checkout -- path/to/file  # discard edits"
echo ""
echo "6) Optional: new branch workflow"
echo "   git checkout -b feature/branch-name"
echo "   git push -u origin feature/branch-name"
echo ""
echo "7) Optional: tags"
echo "   git tag v0.1"
echo "   git push --tags"
echo ""
echo "Credentials are cached via macOS keychain; PAT needed only once."
echo ""
echo "========================================"